:logfile: ./log/development.log
:schedule:
  user_forecast:
    cron: '0 */3 * * *' # Run once every 3 hours
    class: UserForecastWorker
  daily_forecast:
    cron: '0 */3 * * *' # Run once every 3 hours
    class: DailyForecastWorker