:logfile: ./log/development.log
:schedule:
  user_forecast:
    cron: '0 * * * * *' # Run once per minute
    class: UserForecastWorker
  daily_forecast:
    cron: '0 6 * * *' # Run daily at 6am
    class: DailyForecastWorker